In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5])
print(x)
print(x.ndim)

[1 2 3 4 5]
1


In [4]:
# 2D array (matrix)
multi_arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(multi_arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# 3D array
multi_arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(multi_arr_3d)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# 3x4 array of zeros
zeros_arr = np.zeros((3, 4))
print(zeros_arr)

# 2x2 array of ones
ones_arr = np.ones((2, 2))
print(ones_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [6]:
print(f"2D Array dimensions (ndim): {multi_arr_2d.ndim}") # Output: 2
print(f"2D Array shape: {multi_arr_2d.shape}")             # Output: (2, 3)

print(f"3D Array dimensions (ndim): {multi_arr_3d.ndim}") # Output: 3
print(f"3D Array shape: {multi_arr_3d.shape}")             # Output: (2, 2, 2)

2D Array dimensions (ndim): 2
2D Array shape: (2, 3)
3D Array dimensions (ndim): 3
3D Array shape: (2, 2, 2)


In [7]:
rng = np.random.default_rng()

# 2x3 array with random floats between 0.0 and 1.0
random_arr_2d = rng.random((2, 3))
print(random_arr_2d)

# 3x3 array with random integers between a low (inclusive) and high (exclusive) value
random_int_arr = rng.integers(low=0, high=10, size=(3, 3))
print(random_int_arr)

[[0.02118648 0.41392274 0.98103794]
 [0.66279718 0.94847236 0.59297033]]
[[1 6 0]
 [4 4 5]
 [7 0 4]]


In [8]:
# Generate random array

In [9]:
# 'rand' generates random value between 0 and 1
x=np.random.rand(4)
print(x)
print()
x=np.random.rand(4,5)
print(x)

[0.16345275 0.33048142 0.88072819 0.9717669 ]

[[0.07805836 0.42418002 0.83359069 0.72312946 0.44625892]
 [0.40244888 0.07412846 0.42664461 0.88075388 0.21750405]
 [0.8080574  0.08422618 0.0254441  0.98380807 0.91427734]
 [0.84105581 0.74724    0.06074763 0.33914133 0.62452252]]


In [10]:
# 'randn' generates value close to 0 (positive/negativede)
x=np.random.randn(3)
print(x)
print()
x=np.random.randn(2,4)
print(x)

[ 0.79637454 -0.45149257  2.15692464]

[[ 1.655068    0.3471134  -0.4184678   0.0272598 ]
 [-1.45917188 -0.0384161   1.31714416 -0.57588371]]


In [11]:
# 'ranf' generates random number [0.0, 1.0)
x=np.random.ranf(3)
print(x)
print()
x=np.random.ranf((2,4))
print(x)

[0.52141364 0.43235314 0.10871663]

[[0.29959954 0.71799461 0.2626727  0.62220654]
 [0.00320958 0.33309138 0.32454427 0.98327836]]


In [12]:
# 'randint' generates random number between given 2 numbers
x=np.random.randint(3,15,4)
print(x)

[14 13 12  3]


In [13]:
# Data Type
x=np.array([1,2,3,4], dtype=np.int8)
print("Data Type", x.dtype)
print()
x=np.array([1,2,3,4,"A","B","C"])
print("Data Type", x.dtype)

Data Type int8

Data Type <U21


In [19]:
# Numpy arithmatic operations
x=np.array([1,2,3,4])
add=x+4
print(add)

x1=np.array([1,2,3,4])
x2=np.array([4,3,6,7])
add1=x1+x2
print(add1)

[5 6 7 8]
[ 5  5  9 11]


In [21]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,3])
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.mod(x1, x2))

[ 6  8 10  7]
[-4 -4 -4  1]
[ 5 12 21 12]
[0.2        0.33333333 0.42857143 1.33333333]
[1 2 3 1]


In [22]:
x1=np.array([[1,2,3,4], [5,6,7,8]])
x2=np.array([[5,6,7,3], [3,2,0,8]])
print(np.add(x1, x2))

[[ 6  8 10  7]
 [ 8  8  7 16]]


In [24]:
x=np.array([1,2,3,4,5])
print(np.min(x))
print(np.max(x))


1
5


In [28]:
x=np.array([1,2,3,4,5,6])
print(x.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [30]:
x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])
print(x+y)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [35]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)
y=np.array([[1,2],[4,5],[7,8]])
print(y.shape)
print(x*y)

(2, 3)
(3, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 