In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[1.5, 2.5, 3.6], [5.3, 7.4, 2.4]])
print(b)

[[1.5 2.5 3.6]
 [5.3 7.4 2.4]]


In [6]:
# Get dimention
print(a.ndim)

1


In [7]:
# Get shape
print(b.shape)

(2, 3)


In [8]:
# Get type
print(a.dtype)

int64


In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get specific element
print(a[1, 3])

11


In [15]:
# Get specific row
print(a[0,])

[1 2 3 4 5 6 7]


In [17]:
# Get specific column
print(a[:,2])

[ 3 10]


In [19]:
# Little fancy
print(a[1, 1:-1:2])

[ 9 11 13]


In [20]:
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
# 3D Example
b=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [34]:
# Get specific element
print(b[1,1,1])

print(b[:,0])

10
[[1 2]
 [7 8]]


In [36]:
# Replace
b[:,0] = [[8,8],[9,9]]
print(b)

[[[ 8  8]
  [ 3  4]
  [ 5  6]]

 [[ 9  9]
  [ 9 10]
  [11 12]]]


In [45]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
# All 1s matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
# Full matrix
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [59]:
# Random decimal number
# 'rand' returns random number between 0 and 1
print(np.random.rand())
print(np.random.rand(3,4))
# random integer values
print(np.random.randint(8, size=(2,3)))

0.5427153078325719
[[0.55436737 0.71797091 0.24749495 0.21693   ]
 [0.40466734 0.0029559  0.64501013 0.57712699]
 [0.36462373 0.41256947 0.67477195 0.95246096]]
[[2 4 5]
 [6 0 0]]


In [61]:
# Identical array
np.identity(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [65]:
# Repeat
a=np.array([[1,2,3]])
print(np.repeat(a,3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [73]:
a=np.ones((5,5), dtype='int8')
print(a)
b=np.zeros((3,3), dtype='int8')
print(b)
a[1:-1,1:-1]=b
a[2,2]=9
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [74]:
# Copy array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [77]:
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [83]:
a=np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)
b=np.array([2,4,6,8])
print(a+b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 3  6  9 12]


In [89]:
a=np.ones((2,3))
b=np.full((3,2),3)
print(a)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[9. 9.]
 [9. 9.]]


In [94]:
# Statistics
a=np.array([[1,2,3],[4,5,6]])
print(np.min(a))
print(np.max(a))
print(np.max(a, axis=0))
print(np.sum(a, axis=1))

1
6
[4 5 6]
[ 6 15]


In [99]:
# Reorganizing array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b=a.reshape((8,1))
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [103]:
# Vertical Stacking
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack([a,b,a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
# Horizontal Stacking
a=np.ones((4,2))
b=np.zeros((4,2))
np.hstack([a,b])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [119]:
# Miscellaneous
# Load data from file
# np.genfromtxt('demo.txt', delimiter=',', dtype='int8')
filedata=np.genfromtxt('demo.txt', delimiter=',')
filedata=filedata.astype('int16')
filedata

array([[4, 8, 7, 9, 1, 5, 1, 3, 7, 3, 8, 5, 6, 4, 8, 7, 5, 7, 8, 2],
       [4, 7, 6, 2, 4, 3, 3, 7, 1, 1, 4, 5, 4, 1, 1, 3, 5, 6, 3, 8],
       [1, 2, 2, 1, 4, 9, 9, 4, 1, 5, 3, 1, 8, 5, 9, 6, 3, 8, 3, 6]],
      dtype=int16)

## Boolean Masking &Advanced Indexing

In [124]:
print(filedata>5)
print(filedata[filedata>5])

[[False  True  True  True False False False False  True False  True False
   True False  True  True False  True  True False]
 [False  True  True False False False False  True False False False False
  False False False False False  True False  True]
 [False False False False False  True  True False False False False False
   True False  True  True False  True False  True]]
[8 7 9 7 8 6 8 7 7 8 7 6 7 6 8 9 9 8 9 6 8 6]


In [125]:
# Index with a list
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[2,5,8]])

[3 6 9]


In [135]:
print(np.any(filedata>6,axis=0))
print(np.all(filedata>5, axis=0))
print(~((filedata>5) & (filedata<9)))

[False  True  True  True False  True  True  True  True False  True False
  True False  True  True False  True  True  True]
[False False False False False False False False False False False False
 False False False False False  True False False]
[[ True False False  True  True  True  True  True False  True False  True
  False  True False False  True False False  True]
 [ True False False  True  True  True  True False  True  True  True  True
   True  True  True  True  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True  True  True
  False  True  True False  True False  True False]]


In [167]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
print(a)
print(a[2:4, 0:2])
# b=a.reshape((1,30))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]


In [178]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]], dtype='int8')
b=[]
for cell in a.flat:
    b.append(cell)
print(b)

[np.int8(1), np.int8(2), np.int8(3), np.int8(4), np.int8(5), np.int8(6), np.int8(7), np.int8(8), np.int8(9), np.int8(10), np.int8(11), np.int8(12), np.int8(13), np.int8(14), np.int8(15), np.int8(16), np.int8(17), np.int8(18), np.int8(19), np.int8(20), np.int8(21), np.int8(22), np.int8(23), np.int8(24), np.int8(25), np.int8(26), np.int8(27), np.int8(28), np.int8(29), np.int8(30)]
