In [1]:
import numpy as np

In [6]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [7]:
v=np.zeros((2,5))
v

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
v=np.ones((3,4))
v

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
v=np.arange(1,6,2)
v

array([1, 3, 5])

In [17]:
v=np.zeros((2, 3, 4))
print(v)
print(v.shape)  # (2, 3, 4)
print(v.ndim)   # 3
print(v.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
3
24


In [23]:
v=np.eye(4, dtype="int8")
v

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [26]:
v=np.random.rand(3,6)
v

array([[0.07740437, 0.43143429, 0.15031739, 0.16696959, 0.5093363 ,
        0.72205058],
       [0.10170616, 0.81702869, 0.20590138, 0.03029423, 0.71281443,
        0.60997203],
       [0.02934752, 0.84619849, 0.62870247, 0.39533362, 0.37405463,
        0.1664365 ]])

In [28]:
v=np.full((3,5),4)
v

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [34]:
v=np.arange(6).reshape(2,3)
v=v.flatten()
v

array([0, 1, 2, 3, 4, 5])

In [38]:
v1=np.array([[1,2,3],[4,5,6],[7,8,9]])
v2=np.array([[5,3,7],[9,2,5],[1,7,3]])
print(v1+v2)
print((v1+v2).min())

[[ 6  5 10]
 [13  7 11]
 [ 8 15 12]]
5


In [43]:
v=np.array([1,5,2,4,5,8,9,1,4,5])
v1=np.array([3,6,3,5])
print(v)
print(np.concatenate([v,v1]))
print(np.unique(v))
print(np.sort(v1))

[1 5 2 4 5 8 9 1 4 5]
[1 5 2 4 5 8 9 1 4 5 3 6 3 5]
[1 2 4 5 8 9]
[3 3 5 6]


In [49]:
v1=np.random.randint(1,5,size=(3,4))
v2=np.random.randint(1,6,size=(3,4))
print(v1)
print(v2)
print(np.vstack([v1,v2]))
print(np.hstack([v1,v2]))
print(np.hstack([v1,v2]).flatten())

[[1 1 2 3]
 [1 1 3 4]
 [2 1 4 3]]
[[2 3 1 1]
 [2 3 1 2]
 [2 4 4 4]]
[[1 1 2 3]
 [1 1 3 4]
 [2 1 4 3]
 [2 3 1 1]
 [2 3 1 2]
 [2 4 4 4]]
[[1 1 2 3 2 3 1 1]
 [1 1 3 4 2 3 1 2]
 [2 1 4 3 2 4 4 4]]
[1 1 2 3 2 3 1 1 1 1 3 4 2 3 1 2 2 1 4 3 2 4 4 4]


In [59]:
v=np.arange(1,13).reshape(3,4)
v=np.array_split(v,3)
v

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [66]:
v1=np.arange(1,13).reshape(3,4)
v2=np.arange(11,23).reshape(3,4)
v1+v2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [74]:
arr = np.arange(12).reshape(3,4)
print(arr[1, 2])
print(arr[1, :])
print(arr[:,-1])

6
[4 5 6 7]
[ 3  7 11]


In [77]:
arr = np.arange(20).reshape(5,4)
print(arr[1:4])

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [78]:
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [81]:
arr = np.arange(20).reshape(5,4)
print(arr[arr%2==0])

[ 0  2  4  6  8 10 12 14 16 18]
