In [1]:
import numpy as np

#### Numpy indexing and slicing of vectors

In [4]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
arr[5]

np.int64(6)

In [8]:
arr[4:11]

array([ 5,  6,  7,  8,  9, 10, 11])

In [9]:
arr[15:5:-1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7])

#### Numpy indexing and slicing of matrix

In [12]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [14]:
#Get specific row
arr[1]

array([ 7,  8,  9, 10, 11, 12])

In [15]:
# Get specific element
arr[3,4]

np.int64(23)

In [17]:
# Get specific slices
arr[1:4,2:4]

array([[ 9, 10],
       [15, 16],
       [21, 22]])

In [16]:
# Get specific column
arr[:,2]

array([ 3,  9, 15, 21, 27])

#### Boolean indexing

In [19]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [24]:
arr[bool_index]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])