In [1]:
import numpy as np

#### Basic Array Creation

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generation Functions

In [4]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a=np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [7]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [9]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a=np.linspace(1,10,3)
a

array([ 1. ,  5.5, 10. ])

#### Random generation functions

In [11]:
np.random.rand(10)

array([0.79479276, 0.41505867, 0.59320505, 0.64827358, 0.42224646,
       0.2659184 , 0.52001784, 0.33400158, 0.99131762, 0.36859845])

In [12]:
np.random.randint(5)

2

In [13]:
np.random.randint(1,100,10)

array([72,  3, 54, 47, 99, 93, 18, 58, 19, 57], dtype=int32)

#### Array attributes

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 3)
9
int64


#### Array methods

In [17]:
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))

1
9
45


In [18]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

#### Reshaping and resizing

In [19]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [22]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])