In [7]:
import numpy as np

### Array Operations

#### Arithmatic operations

In [8]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [11]:
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)
print(a2%a1)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[0 1 2 1 0]


#### Broadcasting

In [13]:
l=[1,2,3,4,5]
arr=np.array(l)
arr+5

array([ 6,  7,  8,  9, 10])

In [14]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Deep and shallow copy

In [21]:
# Shallow Copy
a=np.arange(1,11)
b=a
b[0]=11
print(b)
print(a)

[11  2  3  4  5  6  7  8  9 10]
[11  2  3  4  5  6  7  8  9 10]


In [23]:
# Deep Copy
arr=np.arange(1,11)
slice=arr[0:5].copy()
slice*=10
print(slice)
print(arr)

[10 20 30 40 50]
[ 1  2  3  4  5  6  7  8  9 10]


#### Matrix operations

In [26]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
# multiplication(dot product)
print(a@b)
# Transpose
print(a.T)
print(a+b)
print(a-b)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


### Advance array manipulation

#### Stacking array

In [29]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [30]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Spliting array

In [40]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
# horizontal split
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [42]:
# vertical split
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]