# Valid Sudoku

In [1]:
import numpy as np

In [17]:
sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [18]:
b=np.sum(sudoku,axis=1)
print(b==45)

c=np.sum(sudoku,axis=0)
print(c==45)

[ True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True]


In [19]:
for i in range(0,9,3):
    for j in range(0,9,3):
        sum=(sudoku[i:i+3,j:j+3]).sum()
        if sum!=45:
            print("Invalid sudoku")
            break

# Questions

In [20]:
# Columns = [Age, Maths, Science]
data=np.array([[18,85,78],[19,92,88],[17,76,95],[18,65,70],[20,90,85]])

In [21]:
# Get the shape of the matrix
data.shape

(5, 3)

In [23]:
# Find the average age of students
data[:,0].mean()

np.float64(18.4)

In [24]:
# Extract Maths marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [25]:
# Find the highest Science marks
data[:,2].max()

np.int64(95)

In [27]:
# Get the details of students who scored more than 90 in Maths
maths_highest=data[:,1]>90
data[maths_highest]

array([[19, 92, 88]])

In [28]:
# Increase Maths marks of all students by 5
maths_marks=data[:,1]+5
maths_marks

array([90, 97, 81, 70, 95])

In [30]:
# Find how many students are younger than 19
under19=data[:,0]<19
data[under19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [32]:
# Calculate avg marks in each subject(column-wise mean)
avg_subject=data[:,1:].mean(axis=0)
avg_subject

array([81.6, 83.2])

In [43]:
# Get data of students who scored atleast 80 in both subjects
more_than_80=((data[:,1]>=80) & (data[:,2]>=80))
data[more_than_80]

array([[19, 92, 88],
       [20, 90, 85]])

In [51]:
# Replace all Science marks < 75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])